/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AttendanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllStudents"
      | "getTotalAttendance"
      | "hasMarkedAttendance"
      | "markAttendance"
      | "studentList"
      | "studentNames"
      | "teacher"
      | "totalAttendance"
      | "verifyAttendance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAttendance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasMarkedAttendance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAttendance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "studentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "studentNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "teacher", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAttendance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttendance",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasMarkedAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teacher", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttendance",
    data: BytesLike
  ): Result;
}

export interface Attendance extends BaseContract {
  connect(runner?: ContractRunner | null): Attendance;
  waitForDeployment(): Promise<this>;

  interface: AttendanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllStudents: TypedContractMethod<[], [[string[], string[]]], "view">;

  getTotalAttendance: TypedContractMethod<[], [bigint], "view">;

  hasMarkedAttendance: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  markAttendance: TypedContractMethod<[name: string], [void], "nonpayable">;

  studentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  studentNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  teacher: TypedContractMethod<[], [string], "view">;

  totalAttendance: TypedContractMethod<[], [bigint], "view">;

  verifyAttendance: TypedContractMethod<
    [student: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllStudents"
  ): TypedContractMethod<[], [[string[], string[]]], "view">;
  getFunction(
    nameOrSignature: "getTotalAttendance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasMarkedAttendance"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markAttendance"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "studentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "studentNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "teacher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAttendance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyAttendance"
  ): TypedContractMethod<[student: AddressLike], [boolean], "view">;

  filters: {};
}
