/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Attendance } from "./Attendance";
export * as factories from "./factories";
export { Attendance__factory } from "./factories/Attendance__factory";
